pbrm/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('PloneBackupRecoverManagement.auth.views',
    #(r'^$', 'login'),
    (r'^login/$', 'login'),
    (r'^logout/$', 'logout'),
)

urlpatterns += patterns('PloneBackupRecoverManagement.recover.views',
    # Examples:
    # url(r'^$', 'PloneBackupRecoverManagement.views.home', name='home'),
    # url(r'^PloneBackupRecoverManagement/', include('PloneBackupRecoverManagement.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    (r'^recover/$', 'index'),
    (r'^recover/do/$', 'do_command'),
    (r'^recover/can_delete/(?P<filename>[\d\-]+\.(fsz|deltafsz))/$', 'can_delete'),
)

urlpatterns += patterns('PloneBackupRecoverManagement.backup.views',
    (r'^backup/$', 'index'),
)

urlpatterns += patterns('PloneBackupRecoverManagement.configuration.views',
    (r'^configure/$', 'index'),
)

urlpatterns += patterns('PloneBackupRecoverManagement.logger.views',
    (r'^log/$', 'index'),
)

pbrm/logger/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _

class Log(models.Model):
    username = models.CharField(max_length=100, help_text=_('Who did the behavior that is associated with this log.'))
    when = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=8, db_index=True)
    succeeded = models.BooleanField(help_text=_('Whether the behavior with which this log is associated succeeded.'))
    detail = models.TextField(help_text=_('Holds the every thing that is printed into the stdout during the backup or recover process.'))

    def __unicode__(self):
        return u'%s at %s by %s' % (self.category, self.when, self.username)

# Helper functions
def log_log(user, category, succeeded, detail):
    log = Log()
    log.username = user.username
    log.category = category
    log.succeeded = succeeded
    log.detail = detail
    log.save()
    return log

def log_backup_log(user, succeeded, detail):
    return log_log(user, 'backup', succeeded, detail)

def log_recover_log(user, succeeded, detail):
    return log_log(user, 'recover', succeeded, detail)

def log_delete_log(user, succeeded, detail):
    return log_log(user, 'delete', succeeded, detail)

pbrm/logger/views.py
# -*- coding: utf-8 -*-

from django import forms
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.core.context_processors import csrf
from django.shortcuts import render_to_response
from django.template import RequestContext

from django.utils.translation import ugettext_lazy as _

from PloneBackupRecoverManagement.logger.models import Log

class LogFilterForm(forms.Form):
    when = forms.DateField(label=_('Logged when'),
                           required=False,
                           input_formats='%Y-%m-%d')
    category = forms.ChoiceField(label=_('Log category'),
                                 choices=(
                                     ('-', _('Not select')),
                                     ('backup', _('Backup')),
                                     ('recover', _('Recover')),
                                 ))
    succeeded = forms.ChoiceField(label=_('Succeeded'),
        choices=(
            ('-', _('Not select')),
            ('yes', _('Yes')),
            ('no', _('No'))
        ))

@login_required
def index(request):
    c = {}

    logs = []

    if request.method == 'POST':
        form = LogFilterForm(request.POST)

        if form.is_valid():
            conditions = []

            when = form.cleaned_data['when']
            if when:
                conditions.append(Q(when=when))

            category = form.cleaned_data['category']
            if category != '-':
                conditions.append(Q(category=category))

            succeeded = form.cleaned_data['succeeded']
            if succeeded != '-':
                conditions.append(Q(succeeded=True if succeeded == 'yes' else False))

            if conditions:
                logs = Log.objects.filter(
                    reduce(lambda x, y: x & y, conditions)).order_by('-when')
            else:
                logs = Log.objects.all().order_by('-when')

    else:
        form = LogFilterForm()
        logs = Log.objects.all().order_by('-when')

    c['form'] = form
    c['logs'] = logs
    return render_to_response('logger/index.html', c,
        context_instance=RequestContext(request))

pbrm/templates/logger/index.html
{% extends "base_view.html" %}
{% load i18n %}
{% block title_description %}View Log{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="/static/css/ui-lightness/jquery-ui.css"></link>
    <link rel="stylesheet" type="text/css" href="/static/css/ui-lightness/jquery.ui.all.css"></link>
    <link rel="stylesheet" type="text/css" href="/static/css/ui-lightness/jquery.ui.datepicker.css"></link>
    <style type="text/css">
        #query_conditions {
            text-align: center;
        }
        #log_list {
            text-align: center;
        }
        #filter_condition {
            list-style-type: none;
            padding: 0px;
            margin-left: 0px;
            margin-right: 0px;
            margin-top: 12px;
            margin-bottom: 12px;
        }
        #filter_condition li {
            display: inline;
        }
    </style>
{% endblock %}
{% block custom_script %}
    <script type="text/javascript" src="/static/js/jquery.ui.core.js"></script>
    <script type="text/javascript" src="/static/js/jquery.ui.datepicker.js"></script>
    <script type="text/javascript" src="/static/js/jquery.ui.widget.js"></script>
    <script type="text/javascript" src="/static/js/jquery.ui.dialog.js"></script>
    <script type="text/javascript" src="/static/js/jquery.ui.mouse.js"></script>
    <script type="text/javascript" src="/static/js/jquery.ui.draggable.js"></script>
    <script type="text/javascript" src="/static/js/jquery.ui.position.js"></script>
    <script type="text/javascript" src="/static/js/jquery.ui.resizable.js"></script>
    <script type="text/javascript" src="/static/js/jquery.bgiframe.js"></script>
    <script type="text/javascript" src="/static/js/i18n/jquery.ui.datepicker-zh-CN.js"></script>
{% endblock %}
{% block content %}
<div id="query_conditions">
    <form method="post">{% csrf_token %}
        <ul id="filter_condition">
            {{ form.as_ul }}
            <li><input type="submit" name="filter" value="{% trans "Filter" %}" /></li>
        </ul>
        <script type="text/javascript">
            $(function() {
                    $.datepicker.setDefaults(
                        $.datepicker.regional[""]);
                    $("#id_when").datepicker(
                        $.datepicker.regional["zh-CN"] );
                    $("#id_when").datepicker("option", "dateFormat", "yy-mm-dd");
                    $("#id_when").datepicker();
            });
        </script>
    </form>
</div>
<div id="log_list">
    <table align="center" cellspacing="0" cellpadding="3" border="0" width="700">
        <tr>
            <th>{% trans "Logged when" %}</th>
            <th>{% trans "Logged by who" %}</th>
            <th>{% trans "Category" %}</th>
            <th>{% trans "Succeeded" %}</th>
            <th>&nbsp;</th>
        </tr>
        {% if logs %}
        <script type="text/javascript">
            // For dialog
            $.fx.speeds._default = 300;
        </script>
        {% for log in logs %}
        <tr>
            <td>{{ log.when }}</td>
            <td>{{ log.username }}</td>
            <td>{{ log.category }}</td>
            <td>{{ log.succeeded}}</td>
            <td>
                <div id="dialog_log_{{ log.id }}" title="{% trans "Log Detail" %}">
                    <p>{{ log.detail|linebreaks }}</p>
                </div>
                <button id="view_detail_log_{{ log.id }}">{% trans "View Detail" %}</button>
                <script type="text/javascript">
                    $(function() {
                            $( "#dialog_log_{{ log.id }}" ).dialog({
                                autoOpen: false,
                                show: "blind",
                                hide: "explode",
                                width: 600,
                            });

                            $("#view_detail_log_{{ log.id }}").click(function() {
                                $("#dialog_log_{{ log.id }}").dialog("open");
                                return false;
                            });
                        });
                </script>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">
                <p>{% trans "No log found." %}</p>
            </td>
        </tr>
        {% endif %}
    </table>
</div>
{% endblock %}